# Site settings
title: thirty-four
email: blog@posnick.org
description: "thirty-four is crafted with love in Brooklyn, by Jeff Posnick."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jeffy.info" # the base hostname & protocol for your site
twitter_username: jeffposnick
github_username:  jeffposnick

# Build settings
markdown: kramdown
exclude: ["node_modules"]
